### PR TITLE
Update Route.php

### PR DESCRIPTION
**Pull request by KasperGreen**
'u' — modifier for unicode support

### CODE REVIEW

**Comment by letr0n** [comment]
Is this needed? It seems to be matching routes with multibyte characters already.

```$routes->get('/ファイナルファンタジー', function()
{
	return 'ファイナルファンタジー';
});```

**Comment by KasperGreen** [comment]
$routes->get('/[\w\-0-9]*-g{id}', 'Index::group'); without 'u' modifier, don`t work in
http://отделочные-материалы.москва/Аквапанели-KNAUF-g13230

but 
$routes->get('/[\w\-0-9А-Яа-я]*-g{id}', 'Index::group');  
work partly and with
http://отделочные-материалы.москва/гипп-g1234 working
http://отделочные-материалы.москва/гипc-g1234 don`t working
ёсшщ etc don`t wokring


sorry for my bad English

**Comment by freost** [comment]
Hi, 

The change looks fine to me. I'll merge it in soon. :+1: 

By the way regex in routes will no longer be supported in version 5 but you can do like this instead (works in both 4.x and 5.x):

```php
$routes->get('/{slug}-g{id}', 'Index::group')->when(['slug' => '[\w\-0-9]*']);
```

**Comment by KasperGreen** [comment]
**freost**, thank you

**Pull request merged**
