### PR TITLE
Update Container.php

### PR DESCRIPTION
**Pull request by twocore**
Syntax error for `return` with conditions.

### CODE REVIEW

**Comment by letr0n** [comment]
```??``` is valid PHP syntax http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by twocore** [comment]
I got the syntax error with PHP 5.6 (Debian Jessie). I think that the backward compatibility should be given, so it is required to use `return <condition> ? <x> : <y>` instead of `??`.

**Comment by freost** [comment]
Hi,

The master branch is for version 5 of the framework which will require PHP 7 when it's released. I would recommend using the [4.5](https://github.com/mako-framework/framework/tree/4.5) branch that only requires PHP 5.5+

**Comment by twocore** [comment]
Hi freost,

i will using the 4.5 branch :-) I didn't know that the master branch is for version 5 of the framework.

**Pull request closed without merging**
